name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: pnpm/action-setup@v6
        with:
          node-version: 11

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run check
