import { SparklesIcon } from "lucide-react";

export default function AiContentWarning() {
  return (
    <div className="flex items-center gap-2 rounded-md bg-card p-2 text-muted-foreground text-xs">
      <SparklesIcon className="size-3" />
      The content in this page may have been generated by AI.
    </div>
  );
}
